org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
kotlin.incremental=false
kotlin.incremental.java=false
# Ép bộ kiểm duyệt JVM chỉ đưa ra cảnh báo hoặc bỏ qua thay vì làm sập dự án (Mẹo tài liệu Kotlin)
kotlin.jvm.target.validation.mode=ignore
# Ép Gradle cho phép thư viện flutter_litert nạp file hệ thống theo kiểu cũ
android.sourceset.disallowProvider=false